version: '2.2'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - E:\Database\Mysql:/var/lib/mysql/
    networks:
      alita:
        ipv4_address: 172.1.0.10
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_connections=3000
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
  backend:
    image: intellinan/mis-java:1.0
    container_name: Jmis
    ports:
      - "9200:9200"
    networks:
      alita:
        ipv4_address: 172.1.0.20
  front:
    image: intellinan/mis-vue:1.0
    container_name: Vmis
    ports:
      - "8080:80"
    networks:
      alita:
        ipv4_address: 172.1.0.30

networks:
  alita:
    external: true
